package ru.croc.ugd.ssr.xml;

import org.junit.Test;
import org.springframework.beans.factory.annotation.Autowired;
import ru.croc.ugd.ssr.BaseRestTest;
import ru.croc.ugd.ssr.model.integration.dgi.SuperServiceDGPPersonsMessage;
import ru.croc.ugd.ssr.mq.listener.PersonResponseListener;
import ru.croc.ugd.ssr.mq.listener.StatusRelocationListener;

public class PersonResponseParseTest extends BaseRestTest {

    @Autowired
    private PersonResponseListener personResponseListener;

    @Autowired
    private StatusRelocationListener statusRelocationListener;

    @Test
    public void parceReciveMessageTest() {
        //SuperServiceDGPPersonsMessage personsMessage = personResponseListener.parseReceiveMessage(message);
        //assertThat(personsMessage.getSuperServiceDGPPersonsResult()).hasSize(48);
        //SuperServiceDGPPersonsMessage message = personResponseListener.parseReceiveMessage(emptyMessage);
    }

    @Test
    public void parseRemovalStatus() {
        statusRelocationListener.parseReceiveMessage(removalStatus);
    }

    private static final String removalStatus = "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n"
            + "<tns:SendTasksMessage xmlns:tns=\"http://asguf.mos.ru/rkis_gu/coordinate/v6_1/\" xmlns:wsu=\"http://docs"
            + ".oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd\" xmlns:xsi=\"http://www.w3"
            + ".org/2001/XMLSchema-instance\" xsi:schemaLocation=\"http://asguf.mos.ru/rkis_gu/coordinate/v6_1/ServiceV6_1_8.xsd\">\n"
            + "<tns:CoordinateTaskDataMessages>\n"
            + "<tns:CoordinateTaskData wsu:Id=\"ID_1\">\n"
            + "<tns:Task>\n"
            + "<tns:MessageId>AFFB1BBB-C2A4-DBAD-E050-400A7E7968B7</tns:MessageId>\n"
            + "<tns:TaskId>AFFB1BBB-C2A9-DBAD-E050-400A7E7968B7</tns:TaskId>\n"
            + "<tns:TaskNumber>2020-09-236257</tns:TaskNumber>\n"
            + "<tns:TaskDate>2020-09-23T15:21:17+03:00</tns:TaskDate>\n"
            + "<tns:Responsible>\n"
            + "<tns:LastName>Петров</tns:LastName>\n"
            + "<tns:FirstName>Петр</tns:FirstName>\n"
            + "<tns:MiddleName>String</tns:MiddleName>\n"
            + "<tns:JobTitle>Директор</tns:JobTitle>\n"
            + "<tns:Phone>123</tns:Phone>\n"
            + "<tns:Email>13@123</tns:Email>\n"
            + "<tns:IsiId>1</tns:IsiId>\n"
            + "<tns:SsoId>2</tns:SsoId>\n"
            + "<tns:MdmId>3</tns:MdmId>\n"
            + "</tns:Responsible>\n"
            + "<tns:Department>\n"
            + "<tns:Name>ДГП</tns:Name>\n"
            + "<tns:Code>String</tns:Code>\n"
            + "<tns:Inn>String</tns:Inn> \n"
            + "<tns:Ogrn>String</tns:Ogrn>\n"
            + "<tns:RegDate>2012-12-17T09:30:47Z</tns:RegDate>\n"
            + "<tns:SystemCode>90154</tns:SystemCode>\n"
            + "</tns:Department>\n"
            + "<tns:ServiceNumber>2591-9000154-067801-0000600/20</tns:ServiceNumber>\n"
            + "<tns:ServiceTypeCode>7777777</tns:ServiceTypeCode>\n"
            + "</tns:Task>\n"
            + "<tns:Data>\n"
            + "<tns:DocumentTypeCode>555</tns:DocumentTypeCode>\n"
            + "<tns:ParameterTypeCode>666</tns:ParameterTypeCode>\n"
            + "<tns:Parameter>\n"
            + "<SuperServiceDGPRemovalStatus>\n"
            + "<new_unom>5034473</new_unom>\n"
            + "<new_cadnum>77:02:0011003:5430</new_cadnum>\n"
            + "<FlatNumber>144</FlatNumber>\n"
            + "<RemovalStatus>9</RemovalStatus>\n"
            + " </SuperServiceDGPRemovalStatus>\n"
            + "</tns:Parameter>\n"
            + "<tns:IncludeXmlView>false</tns:IncludeXmlView>\n"
            + "<tns:IncludeBinaryView>false</tns:IncludeBinaryView> \n"
            + "</tns:Data>\n"
            + "<tns:Signature>text</tns:Signature>\n"
            + "</tns:CoordinateTaskData>\n"
            + "</tns:CoordinateTaskDataMessages>\n"
            + "</tns:SendTasksMessage>\n";

    private static final String message = "<?xml version=\"1.0\" encoding=\"UTF-8\"?> \n"
            + " <tns:CoordinateSendTaskStatusesMessage xsi:schemaLocation=\"http://asguf.mos"
            + ".ru/rkis_gu/coordinate/v6_1/ServiceV6_1_8.xsd\" xmlns:tns=\"http://asguf.mos"
            + ".ru/rkis_gu/coordinate/v6_1/\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"> \n"
            + " <tns:CoordinateTaskStatusDataMessage> \n"
            + " <tns:MessageId>AD3BBF97-640D-B9E6-E050-400A7E795E8E</tns:MessageId> \n"
            + " <tns:TaskId>44ed1114-dcc0-2c6a-aef7-ce0bedd95fb8</tns:TaskId> \n"
            + " <tns:Status> \n"
            + " <tns:StatusCode>0</tns:StatusCode> \n"
            + " <tns:StatusDate>2020-08-19T16:11:57+03:00</tns:StatusDate> \n"
            + " </tns:Status> \n"
            + " <tns:Result> \n"
            + " <tns:ResultType>PositiveAnswer</tns:ResultType> \n"
            + " <tns:ResultCode>0</tns:ResultCode> \n"
            + " <tns:XmlView> \n"
            + "<SuperServiceDGPPersonsMessage>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561409</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>120-504-726 01</snils>\n"
            + "<lastname>Алехина</lastname>\n"
            + "<firstname>Виктория</firstname>\n"
            + "<middlename>Александровна</middlename>\n"
            + "<birthdate>17.08.1980</birthdate>\n"
            + "<sex>Женский</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909947</affair_id>\n"
            + "<statusLiving>Собственник</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>1</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561410</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>118-425-443 49</snils>\n"
            + "<lastname>Алехина</lastname>\n"
            + "<firstname>Ольга</firstname>\n"
            + "<middlename>Александровна</middlename>\n"
            + "<birthdate>22.02.1983</birthdate>\n"
            + "<sex>Женский</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909947</affair_id>\n"
            + "<statusLiving>Собственник</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>1</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561417</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>122-936-592 66</snils>\n"
            + "<lastname>Недзельская</lastname>\n"
            + "<firstname>Татьяна</firstname>\n"
            + "<middlename>Валерьевна</middlename>\n"
            + "<birthdate>21.05.1945</birthdate>\n"
            + "<sex>Женский</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909951</affair_id>\n"
            + "<statusLiving>Собственник</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>4</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561426</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils></snils>\n"
            + "<lastname>Егоров</lastname>\n"
            + "<firstname>Дмитрий</firstname>\n"
            + "<middlename>Петрович</middlename>\n"
            + "<birthdate>18.10.1963</birthdate>\n"
            + "<sex>Мужской</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909953</affair_id>\n"
            + "<statusLiving>Наниматель</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>6</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561430</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>179-969-394 77</snils>\n"
            + "<lastname>Онищенко</lastname>\n"
            + "<firstname>Ника</firstname>\n"
            + "<middlename>Алексеевна</middlename>\n"
            + "<birthdate>13.10.2010</birthdate>\n"
            + "<sex>Женский</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909954</affair_id>\n"
            + "<statusLiving>Собственник</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>7</snos_flat_num>\n"
            + "<snos_rooms_num>2, 3</snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561436</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>022-107-797 09</snils>\n"
            + "<lastname>Сынкова</lastname>\n"
            + "<firstname>Марина</firstname>\n"
            + "<middlename>Викторовна</middlename>\n"
            + "<birthdate>08.04.1961</birthdate>\n"
            + "<sex>Женский</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909958</affair_id>\n"
            + "<statusLiving>Собственник</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>9</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561407</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils></snils>\n"
            + "<lastname>Алёхин</lastname>\n"
            + "<firstname>Дмитрий</firstname>\n"
            + "<middlename>Валентинович</middlename>\n"
            + "<birthdate>02.12.1960</birthdate>\n"
            + "<sex>Мужской</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909947</affair_id>\n"
            + "<statusLiving>Собственник</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>1</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>4278640</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>122-637-436 41</snils>\n"
            + "<lastname>Красиков</lastname>\n"
            + "<firstname>Евгений</firstname>\n"
            + "<middlename>Михайлович</middlename>\n"
            + "<birthdate>04.09.1982</birthdate>\n"
            + "<sex>Мужской</sex>\n"
            + "<IsQueue>Да</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909950</affair_id>\n"
            + "<statusLiving>Проживающий</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>3</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561416</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>094-471-165 82</snils>\n"
            + "<lastname>Ревнова</lastname>\n"
            + "<firstname>Любовь</firstname>\n"
            + "<middlename>Антоновна</middlename>\n"
            + "<birthdate>10.08.1948</birthdate>\n"
            + "<sex>Женский</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909951</affair_id>\n"
            + "<statusLiving>Собственник</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>4</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561441</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>029-516-940 72</snils>\n"
            + "<lastname>Пономарева</lastname>\n"
            + "<firstname>Татьяна</firstname>\n"
            + "<middlename>Павловна</middlename>\n"
            + "<birthdate>03.12.1962</birthdate>\n"
            + "<sex>Женский</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909959</affair_id>\n"
            + "<statusLiving>Проживающий</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>12</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>763514</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>Отсутствует </snils>\n"
            + "<lastname>Отсутствует </lastname>\n"
            + "<firstname>Отсутствует </firstname>\n"
            + "<middlename> </middlename>\n"
            + "<birthdate> </birthdate>\n"
            + "<sex>Отсутствует </sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909962</affair_id>\n"
            + "<statusLiving>Свободная</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>16</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat>Да</noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561451</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>130-767-105 40</snils>\n"
            + "<lastname>Гришина</lastname>\n"
            + "<firstname>Алевтина</firstname>\n"
            + "<middlename>Михайловна</middlename>\n"
            + "<birthdate>12.05.1928</birthdate>\n"
            + "<sex>Женский</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909965</affair_id>\n"
            + "<statusLiving>Проживающий</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>18</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561414</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>078-154-171 76</snils>\n"
            + "<lastname>Архипова</lastname>\n"
            + "<firstname>Юлия</firstname>\n"
            + "<middlename>Вениаминовна</middlename>\n"
            + "<birthdate>02.03.1978</birthdate>\n"
            + "<sex>Женский</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909949</affair_id>\n"
            + "<statusLiving>Собственник</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>2</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>4289254</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>151-562-511 41</snils>\n"
            + "<lastname>Сиротина</lastname>\n"
            + "<firstname>Оксана</firstname>\n"
            + "<middlename>Андреевна</middlename>\n"
            + "<birthdate>09.07.1987</birthdate>\n"
            + "<sex>Женский</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909954</affair_id>\n"
            + "<statusLiving>Собственник</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>7</snos_flat_num>\n"
            + "<snos_rooms_num>2, 3</snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>4892657</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>054-949-866 18</snils>\n"
            + "<lastname>Хренов</lastname>\n"
            + "<firstname>Андрей</firstname>\n"
            + "<middlename>Александрович</middlename>\n"
            + "<birthdate>02.03.1983</birthdate>\n"
            + "<sex>Мужской</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909956</affair_id>\n"
            + "<statusLiving>Собственник</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>8</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561446</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>169-299-315 27</snils>\n"
            + "<lastname>Мартьянова</lastname>\n"
            + "<firstname>Екатерина</firstname>\n"
            + "<middlename>Дмитриевна</middlename>\n"
            + "<birthdate>10.11.1998</birthdate>\n"
            + "<sex>Женский</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909961</affair_id>\n"
            + "<statusLiving>Проживающий</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>15</snos_flat_num>\n"
            + "<snos_rooms_num>1</snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>4278642</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>193-290-958 02</snils>\n"
            + "<lastname>Вихарькова</lastname>\n"
            + "<firstname>Ольга</firstname>\n"
            + "<middlename>Анатольевна</middlename>\n"
            + "<birthdate>19.03.1971</birthdate>\n"
            + "<sex>Женский</sex>\n"
            + "<IsQueue>Да</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909950</affair_id>\n"
            + "<statusLiving>Проживающий</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>3</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561427</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>170-967-697 18</snils>\n"
            + "<lastname>Егоров</lastname>\n"
            + "<firstname>Максим</firstname>\n"
            + "<middlename>Дмитриевич</middlename>\n"
            + "<birthdate>27.04.1991</birthdate>\n"
            + "<sex>Мужской</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909953</affair_id>\n"
            + "<statusLiving>Проживающий</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>6</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561439</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>139-295-615 97</snils>\n"
            + "<lastname>Подгайц</lastname>\n"
            + "<firstname>Александра</firstname>\n"
            + "<middlename>Ефремовна</middlename>\n"
            + "<birthdate>06.11.1990</birthdate>\n"
            + "<sex>Женский</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909959</affair_id>\n"
            + "<statusLiving>Проживающий</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>12</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561444</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>010-244-248 78</snils>\n"
            + "<lastname>Мартьянова</lastname>\n"
            + "<firstname>Людмила</firstname>\n"
            + "<middlename>Валерьевна</middlename>\n"
            + "<birthdate>21.08.1970</birthdate>\n"
            + "<sex>Женский</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909961</affair_id>\n"
            + "<statusLiving>Проживающий</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>15</snos_flat_num>\n"
            + "<snos_rooms_num>1</snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6562294</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>122-607-124 13</snils>\n"
            + "<lastname>Шакирзянова</lastname>\n"
            + "<firstname>Айгуль</firstname>\n"
            + "<middlename>Мурзагалеевна</middlename>\n"
            + "<birthdate>27.08.1982</birthdate>\n"
            + "<sex>Женский</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909971</affair_id>\n"
            + "<statusLiving>Собственник</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>17</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>4278645</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>170-171-289 40</snils>\n"
            + "<lastname>Вихарьков</lastname>\n"
            + "<firstname>Александр</firstname>\n"
            + "<middlename>Григорьевич</middlename>\n"
            + "<birthdate>27.04.1992</birthdate>\n"
            + "<sex>Мужской</sex>\n"
            + "<IsQueue>Да</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909950</affair_id>\n"
            + "<statusLiving>Проживающий</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>3</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561443</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>066-079-040 68</snils>\n"
            + "<lastname>Мартьянов</lastname>\n"
            + "<firstname>Дмитрий</firstname>\n"
            + "<middlename>Александрович</middlename>\n"
            + "<birthdate>18.02.1969</birthdate>\n"
            + "<sex>Мужской</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909961</affair_id>\n"
            + "<statusLiving>Наниматель</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>15</snos_flat_num>\n"
            + "<snos_rooms_num>1</snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561452</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>119-193-443 65</snils>\n"
            + "<lastname>Гришина</lastname>\n"
            + "<firstname>Валентина</firstname>\n"
            + "<middlename>Александровна</middlename>\n"
            + "<birthdate>16.08.1957</birthdate>\n"
            + "<sex>Женский</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909965</affair_id>\n"
            + "<statusLiving>Наниматель</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>18</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>4711861</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>001-583-440 08</snils>\n"
            + "<lastname>Мартынов</lastname>\n"
            + "<firstname>Владимир</firstname>\n"
            + "<middlename>Николаевич</middlename>\n"
            + "<birthdate>16.05.1954</birthdate>\n"
            + "<sex>Мужской</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909966</affair_id>\n"
            + "<statusLiving>Собственник</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>10</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561457</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>149-098-055 95</snils>\n"
            + "<lastname>Жигалина</lastname>\n"
            + "<firstname>Анастасия</firstname>\n"
            + "<middlename>Анатольевна</middlename>\n"
            + "<birthdate>26.04.1996</birthdate>\n"
            + "<sex>Женский</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909967</affair_id>\n"
            + "<statusLiving>Пользователь</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>11</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6562291</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>055-197-060 65</snils>\n"
            + "<lastname>Фридрихсон</lastname>\n"
            + "<firstname>Вероника</firstname>\n"
            + "<middlename>Юрьевна</middlename>\n"
            + "<birthdate>18.11.1977</birthdate>\n"
            + "<sex>Женский</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909970</affair_id>\n"
            + "<statusLiving>Собственник</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>14</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561408</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>023-013-002 56</snils>\n"
            + "<lastname>Алексеева</lastname>\n"
            + "<firstname>Елена</firstname>\n"
            + "<middlename>Николаевна</middlename>\n"
            + "<birthdate>04.11.1961</birthdate>\n"
            + "<sex>Женский</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909947</affair_id>\n"
            + "<statusLiving>Собственник</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>1</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>4278637</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>049-094-668 93</snils>\n"
            + "<lastname>Красиков</lastname>\n"
            + "<firstname>Михаил</firstname>\n"
            + "<middlename>Васильевич</middlename>\n"
            + "<birthdate>20.11.1951</birthdate>\n"
            + "<sex>Мужской</sex>\n"
            + "<IsQueue>Да</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909950</affair_id>\n"
            + "<statusLiving>Наниматель</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>3</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561453</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>133-445-965 61</snils>\n"
            + "<lastname>Гришин</lastname>\n"
            + "<firstname>СТАНИСЛАВ</firstname>\n"
            + "<middlename>ВЯЧЕСЛАВОВИЧ</middlename>\n"
            + "<birthdate>10.12.1985</birthdate>\n"
            + "<sex>Мужской</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909965</affair_id>\n"
            + "<statusLiving>Проживающий</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>18</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>4711873</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>146-473-746 88</snils>\n"
            + "<lastname>Мартынова</lastname>\n"
            + "<firstname>Нина</firstname>\n"
            + "<middlename>Васильевна</middlename>\n"
            + "<birthdate>19.08.1954</birthdate>\n"
            + "<sex>Женский</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909966</affair_id>\n"
            + "<statusLiving>Собственник</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>10</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>4711883</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>155-760-534 80</snils>\n"
            + "<lastname>Мартынов</lastname>\n"
            + "<firstname>Константин</firstname>\n"
            + "<middlename>Владимирович</middlename>\n"
            + "<birthdate>03.11.1990</birthdate>\n"
            + "<sex>Мужской</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909966</affair_id>\n"
            + "<statusLiving>Собственник</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>10</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561456</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>037-119-054 33</snils>\n"
            + "<lastname>Жигалина</lastname>\n"
            + "<firstname>Людмила</firstname>\n"
            + "<middlename>Николаевна</middlename>\n"
            + "<birthdate>26.01.1953</birthdate>\n"
            + "<sex>Женский</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909967</affair_id>\n"
            + "<statusLiving>Собственник</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>11</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561459</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>063-362-522 45</snils>\n"
            + "<lastname>Чернышова</lastname>\n"
            + "<firstname>Елена</firstname>\n"
            + "<middlename>Владимировна</middlename>\n"
            + "<birthdate>27.04.1965</birthdate>\n"
            + "<sex>Женский</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909968</affair_id>\n"
            + "<statusLiving>Пользователь</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>13</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6579320</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils></snils>\n"
            + "<lastname>Вихарькова</lastname>\n"
            + "<firstname>Вероника</firstname>\n"
            + "<middlename>Александровна</middlename>\n"
            + "<birthdate>25.03.2020</birthdate>\n"
            + "<sex>Женский</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909950</affair_id>\n"
            + "<statusLiving>Проживающий</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>3</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561420</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>013-765-156 39</snils>\n"
            + "<lastname>Сидорова</lastname>\n"
            + "<firstname>Татьяна</firstname>\n"
            + "<middlename>Григорьевна</middlename>\n"
            + "<birthdate>05.03.1957</birthdate>\n"
            + "<sex>Женский</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909952</affair_id>\n"
            + "<statusLiving>Собственник</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>5</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561440</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>179-977-623 68</snils>\n"
            + "<lastname>Пономарев</lastname>\n"
            + "<firstname>Георгий</firstname>\n"
            + "<middlename>Владимирович</middlename>\n"
            + "<birthdate>31.08.1996</birthdate>\n"
            + "<sex>Мужской</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909959</affair_id>\n"
            + "<statusLiving>Проживающий</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>12</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561442</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>164-779-227 13</snils>\n"
            + "<lastname>Карамышев</lastname>\n"
            + "<firstname>Дмитрий</firstname>\n"
            + "<middlename>Олегович</middlename>\n"
            + "<birthdate>30.12.1995</birthdate>\n"
            + "<sex>Мужской</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909960</affair_id>\n"
            + "<statusLiving>Собственник</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>15</snos_flat_num>\n"
            + "<snos_rooms_num>2, 3</snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6562292</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils></snils>\n"
            + "<lastname>Карамышева</lastname>\n"
            + "<firstname>Юлия</firstname>\n"
            + "<middlename>Юорисовна</middlename>\n"
            + "<birthdate>26.10.1970</birthdate>\n"
            + "<sex>Женский</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909960</affair_id>\n"
            + "<statusLiving>Собственник</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>15</snos_flat_num>\n"
            + "<snos_rooms_num>2, 3</snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>4711890</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>112-501-637 96</snils>\n"
            + "<lastname>Мартынов</lastname>\n"
            + "<firstname>Игорь</firstname>\n"
            + "<middlename>Владимирович</middlename>\n"
            + "<birthdate>05.10.1983</birthdate>\n"
            + "<sex>Мужской</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909966</affair_id>\n"
            + "<statusLiving>Собственник</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>10</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561458</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>052-374-585 58</snils>\n"
            + "<lastname>Кабаков</lastname>\n"
            + "<firstname>Семен</firstname>\n"
            + "<middlename>Юрьевич</middlename>\n"
            + "<birthdate>24.01.1956</birthdate>\n"
            + "<sex>Мужской</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909968</affair_id>\n"
            + "<statusLiving>Собственник</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>13</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561411</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>205-545-355 46</snils>\n"
            + "<lastname>Алехина</lastname>\n"
            + "<firstname>Александра</firstname>\n"
            + "<middlename>Александровна</middlename>\n"
            + "<birthdate>30.04.2019</birthdate>\n"
            + "<sex>Женский</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909947</affair_id>\n"
            + "<statusLiving>Пользователь</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>1</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561425</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>116-492-034 45</snils>\n"
            + "<lastname>Егорова</lastname>\n"
            + "<firstname>Лидия</firstname>\n"
            + "<middlename>Михайловна</middlename>\n"
            + "<birthdate>07.01.1929</birthdate>\n"
            + "<sex>Женский</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909953</affair_id>\n"
            + "<statusLiving>Проживающий</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>6</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561429</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>037-784-374 97</snils>\n"
            + "<lastname>Гужев</lastname>\n"
            + "<firstname>Сергей</firstname>\n"
            + "<middlename>Николаевич</middlename>\n"
            + "<birthdate>17.02.1958</birthdate>\n"
            + "<sex>Мужской</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909955</affair_id>\n"
            + "<statusLiving>Собственник</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>7</snos_flat_num>\n"
            + "<snos_rooms_num>1</snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561434</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>148-174-907 87</snils>\n"
            + "<lastname>Беляева</lastname>\n"
            + "<firstname>Наталья</firstname>\n"
            + "<middlename>Васильевна</middlename>\n"
            + "<birthdate>16.03.1990</birthdate>\n"
            + "<sex>Женский</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909956</affair_id>\n"
            + "<statusLiving>Собственник</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>8</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561437</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>022-582-280 29</snils>\n"
            + "<lastname>Пономарева</lastname>\n"
            + "<firstname>Ирина</firstname>\n"
            + "<middlename>Сергеевна</middlename>\n"
            + "<birthdate>16.03.1951</birthdate>\n"
            + "<sex>Женский</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909959</affair_id>\n"
            + "<statusLiving>Наниматель</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>12</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561438</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>146-697-935 28</snils>\n"
            + "<lastname>Пономарев</lastname>\n"
            + "<firstname>Владимир</firstname>\n"
            + "<middlename>Сергеевич</middlename>\n"
            + "<birthdate>22.12.1954</birthdate>\n"
            + "<sex>Мужской</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909959</affair_id>\n"
            + "<statusLiving>Проживающий</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>12</snos_flat_num>\n"
            + "<snos_rooms_num></snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "<SuperServiceDGPPersonsResult>\n"
            + "<person_id>6561445</person_id>\n"
            + "<actual_date></actual_date>\n"
            + "<snils>159-659-970 48</snils>\n"
            + "<lastname>Мартьянова</lastname>\n"
            + "<firstname>Анастасия</firstname>\n"
            + "<middlename>Дмитриевна</middlename>\n"
            + "<birthdate>12.09.1995</birthdate>\n"
            + "<sex>Женский</sex>\n"
            + "<IsQueue>Нет</IsQueue>\n"
            + "<IsDead></IsDead>\n"
            + "<ChangeStatus>Начальная загрузка </ChangeStatus>\n"
            + "<delReason></delReason>\n"
            + "<LinkedFlats>\n"
            + "<Flat>\n"
            + "<affair_id>909961</affair_id>\n"
            + "<statusLiving>Проживающий</statusLiving>\n"
            + "<encumbrances>Нет данных</encumbrances>\n"
            + "<snos_unom>3711</snos_unom>\n"
            + "<snos_cadnum>77:02:0015004:1007</snos_cadnum>\n"
            + "<snos_flat_num>15</snos_flat_num>\n"
            + "<snos_rooms_num>1</snos_rooms_num>\n"
            + "<noFlat> </noFlat>\n"
            + "<isFederal></isFederal>\n"
            + "<inCourt>Нет</inCourt>\n"
            + " </Flat>\n"
            + "</LinkedFlats>\n"
            + "</SuperServiceDGPPersonsResult>\n"
            + "</SuperServiceDGPPersonsMessage>\n"
            + " </tns:XmlView>\n"
            + "</tns:Result>\n"
            + "</tns:CoordinateTaskStatusDataMessage>\n"
            + "</tns:CoordinateSendTaskStatusesMessage>";

    private static final String emptyMessage = "<?xml version=\"1.0\" encoding=\"UTF-8\"?> \n"
        + " <tns:CoordinateSendTaskStatusesMessage xsi:schemaLocation=\"http://asguf.mos.ru/rkis_gu/coordinate/v6_1/ServiceV6_1_8.xsd\" xmlns:tns=\"http://asguf.mos.ru/rkis_gu/coordinate/v6_1/\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"> \n"
        + " <tns:CoordinateTaskStatusDataMessage> \n"
        + " <tns:MessageId>AD3BBCC6-2F3B-83E7-E050-400A7E795E6C</tns:MessageId> \n"
        + " <tns:TaskId>44ed1114-dcc0-3c6a-aef7-ce0bedd95fb8</tns:TaskId> \n"
        + " <tns:Status> \n"
        + " <tns:StatusCode>404</tns:StatusCode> \n"
        + " <tns:StatusDate>2020-08-19T16:11:10+03:00</tns:StatusDate> \n"
        + " </tns:Status> \n"
        + " <tns:Result> \n"
        + " <tns:ResultType>PositiveAnswer</tns:ResultType> \n"
        + " <tns:ResultCode>0</tns:ResultCode> \n"
        + " <tns:XmlView> \n"
        + "<SuperServiceDGPPersonsMessage> \n"
        + "</SuperServiceDGPPersonsMessage>\n"
        + " </tns:XmlView>\n"
        + "</tns:Result>\n"
        + "</tns:CoordinateTaskStatusDataMessage>\n"
        + "</tns:CoordinateSendTaskStatusesMessage>";
}
