#app:
#  security:
#    enabled: false

userprofile:
  url: http://nginx.cdp.local:8085/userprofile

management:
  endpoint:
    health:
      show-details: "when_authorized"

spring:
  liquibase:
    contexts: dev
  jpa:
    properties:
      hibernate.format_sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

schedulers:
  shipping-check:
    enabled: true
    cron: 50 * * * * ?

exception-handler:
  show-stacktrace: true

ugd:
  ssr:
    apartment-inspection:
      default-tech-user-org: NO_SUCH_ORG
      kp-ugs-inn: 7719272800
    listener:
      shipping:
        enabled: false
      commission-inspection:
        enabled: false
      notary-application:
        enabled: false
      personal-document-application:
        enabled: false
    person-letter-and-contract-upload:
      order-id:
        column-name: "ORDER_ID"
        column-index: 26
    mfr-flow:
      enabled: true

ibm:
  mq:
    guo:
      enabled: true
      queue-manager: GU01QM
      channel: CLIENT.GUO.SVRCONN
      user: guo
      password: guo
    queue:
      elk-ms:
        out: UGD_MS.NOTIFICATION_OUT
        statusOut: UGD_MS.NOTIFICATION_STATUS_OUT
