mqetpmv:
  etp-profiles:
    # Запрос объектов капитального строительства
    UGD_RSM_COURT_TASK_INC:
      message-type: UGD_RSM_COURT_TASK_INC
      inbound: true
      queue-manager: GU01QM
      channel: CLIENT.UGD.SVRCONN
      username: ugd
      password: ugd
      queue: RENOVATION.DGP.COURT
      subscriber: /app/ugd/ssr
      cron: 0 0/1 * * * *
    UGD_RSM_COURT_STATUS_OUT:
      message-type: UGD_RSM_COURT_STATUS_OUT
      inbound: false
      queue-manager: GU01QM
      channel: CLIENT.UGD.SVRCONN
      username: ugd
      password: ugd
      queue: RENOVATION.ETP.COURT_DEL
    # Поток ДГИ №19. Сведения об инвалидах
    UGD_RSM_DISABLED_PERSON_STATUS_INC:
      message-type: UGD_RSM_DISABLED_PERSON_STATUS_INC
      inbound: true
      queue-manager: GU01QM
      channel: CLIENT.UGD.SVRCONN
      username: ugd
      password: ugd
      queue: RENOVATION.DGP.DISABLED_PERSON_DEL
      subscriber: /app/ugd/ssr
      cron: 0 0/1 * * * *
    UGD_RSM_DISABLED_PERSON_TASK_OUT:
      message-type: UGD_RSM_DISABLED_PERSON_TASK_OUT
      inbound: false
      queue-manager: GU01QM
      channel: CLIENT.UGD.SVRCONN
      username: ugd
      password: ugd
      queue: RENOVATION.ETP.DISABLED_PERSON
    # Поток ДГИ №17. Сведения по докупке и компенсации
    UGD_APT_ADDITIONAL_STATUS_INC:
      message-type: UGD_APT_ADDITIONAL_STATUS_INC
      inbound: true
      queue-manager: GU01QM
      channel: CLIENT.UGD.SVRCONN
      username: ugd
      password: ugd
      queue: RENOVATION.DGP.APT_ADDITIONAL_DEL
      subscriber: /app/ugd/ssr
      cron: 0 0/1 * * * *
    UGD_APT_ADDITIONAL_TASK_OUT:
      message-type: UGD_APT_ADDITIONAL_TASK_OUT
      inbound: false
      queue-manager: GU01QM
      channel: CLIENT.UGD.SVRCONN
      username: ugd
      password: ugd
      queue: RENOVATION.ETP.APT_ADDITIONAL
    # Поток ДГИ №20. Сведения о квартирографии
    UGD_FLAT_LAYOUT_STATUS_INC:
      message-type: UGD_FLAT_LAYOUT_STATUS_INC
      inbound: true
      queue-manager: GU01QM
      channel: CLIENT.UGD.SVRCONN
      username: ugd
      password: ugd
      queue: RENOVATION.DGP.PROJECT_APARTMENTOGRAPHY_DEL
      subscriber: /app/ugd/ssr
      cron: 0 0/1 * * * *
    UGD_FLAT_LAYOUT_TASK_OUT:
      message-type: UGD_FLAT_LAYOUT_TASK_OUT
      inbound: false
      queue-manager: GU01QM
      channel: CLIENT.UGD.SVRCONN
      username: ugd
      password: ugd
      queue: RENOVATION.ETP.PROJECT_APARTMENTOGRAPHY
    # Поток ДГИ №18. Сведения для сверки жителей
    UGD_AFFAIR_COLLATION_STATUS_INC:
      message-type: UGD_AFFAIR_COLLATION_STATUS_INC
      inbound: true
      queue-manager: GU01QM
      channel: CLIENT.UGD.SVRCONN
      username: ugd
      password: ugd
      queue: RENOVATION.DGP.REPORT
      subscriber: /app/ugd/ssr
      cron: 0 0/1 * * * *
    # Поток ДГИ №18. Отчет о сверке жителей
    UGD_AFFAIR_COLLATION_TASK_OUT:
      message-type: UGD_AFFAIR_COLLATION_TASK_OUT
      inbound: false
      queue-manager: GU01QM
      channel: CLIENT.UGD.SVRCONN
      username: ugd
      password: ugd
      queue: RENOVATION.ETP.REQUEST_CITIZEN
    # Поток ДГИ №1. Сведения о жителях
    UGD_PERSON_RESPONSE_INC:
      message-type: UGD_PERSON_RESPONSE_INC
      inbound: true
      queue-manager: GU01QM
      channel: CLIENT.UGD.SVRCONN
      username: ugd
      password: ugd
      queue: RENOVATION.UGD.PERSONS_RES
      subscriber: /app/ugd/ssr
      cron: 0 0/1 * * * *
    # Поток ДГИ №1. Сведения об изменениях по жителям
    UGD_PERSON_UPDATE_INC:
      message-type: UGD_PERSON_UPDATE_INC
      inbound: true
      queue-manager: GU01QM
      channel: CLIENT.UGD.SVRCONN
      username: ugd
      password: ugd
      queue: RENOVATION.UGD.PERSONS_UPD_REQ
      subscriber: /app/ugd/ssr
      cron: 0 0/1 * * * *
    # Поток ДГИ №2. Сведения о письмах с предложениями
    UGD_OFFER_LETTER_INC:
      message-type: UGD_OFFER_LETTER_INC
      inbound: true
      queue-manager: GU01QM
      channel: CLIENT.UGD.SVRCONN
      username: ugd
      password: ugd
      queue: RENOVATION.UGD.LETTERS_REQ
      subscriber: /app/ugd/ssr
      cron: 0 0/1 * * * *
    # Поток ДГИ №4. Сведения о статусе переселения квартир
    UGD_STATUS_RELOCATION_INC:
      message-type: UGD_STATUS_RELOCATION_INC
      inbound: true
      queue-manager: GU01QM
      channel: CLIENT.UGD.SVRCONN
      username: ugd
      password: ugd
      queue: RENOVATION.UGD.RELOCATION_REQ
      subscriber: /app/ugd/ssr
      cron: 0 0/1 * * * *
    # Поток ДГИ №7. Сведения о готовности договора
    UGD_CONTRACT_READY_INC:
      message-type: UGD_CONTRACT_READY_INC
      inbound: true
      queue-manager: GU01QM
      channel: CLIENT.UGD.SVRCONN
      username: ugd
      password: ugd
      queue: RENOVATION.DGP.APT_DRAFT
      subscriber: /app/ugd/ssr
      cron: 0 0/1 * * * *
    # Поток ДГИ №8. Сведения о переселении по решению суда и равноценном возмещении
    UGD_CONTRACT_SIGNED_INC:
      message-type: UGD_CONTRACT_SIGNED_INC
      inbound: true
      queue-manager: GU01QM
      channel: CLIENT.UGD.SVRCONN
      username: ugd
      password: ugd
      queue: RENOVATION.DGP.APT_COURT
      subscriber: /app/ugd/ssr
      cron: 0 0/1 * * * *
    # Поток ДГИ №8. Сведения о регистрации договора
    UGD_CONTRACT_REGISTER_INC:
      message-type: UGD_CONTRACT_REGISTER_INC
      inbound: true
      queue-manager: GU01QM
      channel: CLIENT.UGD.SVRCONN
      username: ugd
      password: ugd
      queue: RENOVATION.DGP.APT_REG
      subscriber: /app/ugd/ssr
      cron: 0 0/1 * * * *
    # Поток ДГИ №8. Сведения о заселяемой квартире
    UGD_INFO_SETTLEMENT_INC:
      message-type: UGD_INFO_SETTLEMENT_INC
      inbound: true
      queue-manager: GU01QM
      channel: CLIENT.UGD.SVRCONN
      username: ugd
      password: ugd
      queue: RENOVATION.DGP.APT_FLAT
      subscriber: /app/ugd/ssr
      cron: 0 0/1 * * * *
    # Поток ДГИ №12. Сведения о готовности проекта договора
    UGD_CONTRACT_PR_READY_INC:
      message-type: UGD_CONTRACT_PR_READY_INC
      inbound: true
      queue-manager: GU01QM
      channel: CLIENT.UGD.SVRCONN
      username: ugd
      password: ugd
      queue: RENOVATION.DGP.APT_DRAFTTWO
      subscriber: /app/ugd/ssr
      cron: 0 0/1 * * * *
    # Поток ДГИ №13. Сведения о передаче распорядительного документа
    UGD_ADMINISTRATIVE_DOCUMENT_INC:
      message-type: UGD_ADMINISTRATIVE_DOCUMENT_INC
      inbound: true
      queue-manager: GU01QM
      channel: CLIENT.UGD.SVRCONN
      username: ugd
      password: ugd
      queue: RENOVATION.DGP.APT_ADMINISTRATIVE
      subscriber: /app/ugd/ssr
      cron: 0 0/1 * * * *
