//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.14 at 01:15:24 PM MSK 
//


package ru.croc.ugd.ssr.model.integration.shipping;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Адрес
 *
 * <p>Java class for Address complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Address"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Unom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Text" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *         &lt;element name="Room" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Entrance" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Entrance_code" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Floor" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Address", propOrder = {
        "unom",
        "text",
        "room",
        "entrance",
        "entranceCode",
        "floor"
})
public class Address {

    @XmlElement(name = "Unom", namespace = "http://mos.ru/gu/service/054201/", required = true)
    protected String unom;
    @XmlElement(name = "Text", namespace = "http://mos.ru/gu/service/054201/", required = true)
    protected String text;
    @XmlElement(name = "Room", namespace = "http://mos.ru/gu/service/054201/")
    protected String room;
    @XmlElement(name = "Entrance", namespace = "http://mos.ru/gu/service/054201/", required = true)
    protected String entrance;
    @XmlElement(name = "Entrance_code", namespace = "http://mos.ru/gu/service/054201/", required = true)
    protected String entranceCode;
    @XmlElement(name = "Floor", namespace = "http://mos.ru/gu/service/054201/", required = true)
    protected String floor;

    /**
     * Gets the value of the unom property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getUnom() {
        return unom;
    }

    /**
     * Sets the value of the unom property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setUnom(String value) {
        this.unom = value;
    }

    /**
     * Gets the value of the text property.
     *
     * @return possible object is
     * {@link Object }
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     *
     * @param value allowed object is
     *              {@link Object }
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the room property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRoom() {
        return room;
    }

    /**
     * Sets the value of the room property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRoom(String value) {
        this.room = value;
    }

    /**
     * Gets the value of the entrance property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEntrance() {
        return entrance;
    }

    /**
     * Sets the value of the entrance property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEntrance(String value) {
        this.entrance = value;
    }

    /**
     * Gets the value of the entranceCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEntranceCode() {
        return entranceCode;
    }

    /**
     * Sets the value of the entranceCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEntranceCode(String value) {
        this.entranceCode = value;
    }

    /**
     * Gets the value of the floor property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFloor() {
        return floor;
    }

    /**
     * Sets the value of the floor property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFloor(String value) {
        this.floor = value;
    }

}
