//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.10.29 at 05:12:42 PM MSK
//


package ru.croc.ugd.ssr.model.integration.shipping;

import ru.reinform.cdp.utils.mapper.xml.LocalDateTimeXmlAdapter;

import java.time.LocalDateTime;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="ExtPhone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="UnomOld" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="AddressOld" type="{}Address"/&gt;
 *         &lt;element name="UnomNew" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="AddressNew" type="{}Address"/&gt;
 *         &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="RemovalDateTimeStart" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="RemovalDateTimeEnd" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="Confirm1" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Confirm2" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Confirm3" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="BookingUid" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "http://mos.ru/gu/service/054201/", propOrder = {

})
@XmlRootElement(name = "ServiceProperties", namespace="http://mos.ru/gu/service/054201/")
public class ServiceProperties {
    @XmlElement(name = "ExtPhone",  namespace = "http://mos.ru/gu/service/054201/")
    protected String extPhone;
    @XmlElement(name = "AddressOld",  namespace = "http://mos.ru/gu/service/054201/", required = true)
    protected Address addressOld;
    @XmlElement(name = "AddressNew",  namespace = "http://mos.ru/gu/service/054201/", required = true)
    protected Address addressNew;
    @XmlElement(name = "Notes",  namespace = "http://mos.ru/gu/service/054201/")
    protected String notes;
    @XmlElement(name = "RemovalDateTimeStart",  namespace = "http://mos.ru/gu/service/054201/", required = true, type = String.class)
    @XmlJavaTypeAdapter(LocalDateTimeXmlAdapter.class)
    @XmlSchemaType(name = "dateTime")
    protected LocalDateTime removalDateTimeStart;
    @XmlElement(name = "RemovalDateTimeEnd",  namespace = "http://mos.ru/gu/service/054201/", required = true, type = String.class)
    @XmlJavaTypeAdapter(LocalDateTimeXmlAdapter.class)
    @XmlSchemaType(name = "dateTime")
    protected LocalDateTime removalDateTimeEnd;
    @XmlElement(name = "Confirm1",  namespace = "http://mos.ru/gu/service/054201/")
    protected boolean confirm1;
    @XmlElement(name = "Confirm2",  namespace = "http://mos.ru/gu/service/054201/")
    protected boolean confirm2;
    @XmlElement(name = "Confirm3",  namespace = "http://mos.ru/gu/service/054201/")
    protected boolean confirm3;
    @XmlElement(name = "BookingUid",  namespace = "http://mos.ru/gu/service/054201/", required = true)
    protected String bookingUid;

    /**
     * Gets the value of the extPhone property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getExtPhone() {
        return extPhone;
    }

    /**
     * Sets the value of the extPhone property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setExtPhone(String value) {
        this.extPhone = value;
    }

    /**
     * Gets the value of the addressOld property.
     *
     * @return
     *     possible object is
     *     {@link ru.croc.ugd.ssr.shipping.Address }
     *
     */
    public Address getAddressOld() {
        return addressOld;
    }

    /**
     * Sets the value of the addressOld property.
     *
     * @param value
     *     allowed object is
     *     {@link ru.croc.ugd.ssr.shipping.Address }
     *
     */
    public void setAddressOld(Address value) {
        this.addressOld = value;
    }

    /**
     * Gets the value of the addressNew property.
     *
     * @return
     *     possible object is
     *     {@link ru.croc.ugd.ssr.shipping.Address }
     *
     */
    public Address getAddressNew() {
        return addressNew;
    }

    /**
     * Sets the value of the addressNew property.
     *
     * @param value
     *     allowed object is
     *     {@link ru.croc.ugd.ssr.shipping.Address }
     *
     */
    public void setAddressNew(Address value) {
        this.addressNew = value;
    }

    /**
     * Gets the value of the notes property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the removalDateTimeStart property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public LocalDateTime getRemovalDateTimeStart() {
        return removalDateTimeStart;
    }

    /**
     * Sets the value of the removalDateTimeStart property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRemovalDateTimeStart(LocalDateTime value) {
        this.removalDateTimeStart = value;
    }

    /**
     * Gets the value of the removalDateTimeEnd property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public LocalDateTime getRemovalDateTimeEnd() {
        return removalDateTimeEnd;
    }

    /**
     * Sets the value of the removalDateTimeEnd property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRemovalDateTimeEnd(LocalDateTime value) {
        this.removalDateTimeEnd = value;
    }

    /**
     * Gets the value of the confirm1 property.
     *
     */
    public boolean isConfirm1() {
        return confirm1;
    }

    /**
     * Sets the value of the confirm1 property.
     *
     */
    public void setConfirm1(boolean value) {
        this.confirm1 = value;
    }

    /**
     * Gets the value of the confirm2 property.
     *
     */
    public boolean isConfirm2() {
        return confirm2;
    }

    /**
     * Sets the value of the confirm2 property.
     *
     */
    public void setConfirm2(boolean value) {
        this.confirm2 = value;
    }

    /**
     * Gets the value of the confirm3 property.
     *
     */
    public boolean isConfirm3() {
        return confirm3;
    }

    /**
     * Sets the value of the confirm3 property.
     *
     */
    public void setConfirm3(boolean value) {
        this.confirm3 = value;
    }

    /**
     * Gets the value of the bookingUid property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBookingUid() {
        return bookingUid;
    }

    /**
     * Sets the value of the bookingUid property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBookingUid(String value) {
        this.bookingUid = value;
    }

}
