//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.22 at 04:14:48 PM MSK 
//


package ru.croc.ugd.ssr.model.integration.asur.apartmentdata;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ssr package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DatalistDocs_QNAME = new QName("", "docs");
    private final static QName _DatalistPrefList_QNAME = new QName("", "pref_list");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ssr
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Datalist }
     * 
     */
    public Datalist createDatalist() {
        return new Datalist();
    }

    /**
     * Create an instance of {@link Datalist.DolgPer }
     * 
     */
    public Datalist.DolgPer createDatalistDolgPer() {
        return new Datalist.DolgPer();
    }

    /**
     * Create an instance of {@link Datalist.DolgPer.Servs }
     * 
     */
    public Datalist.DolgPer.Servs createDatalistDolgPerServs() {
        return new Datalist.DolgPer.Servs();
    }

    /**
     * Create an instance of {@link Datalist.DolgPer.Servs.Serv }
     * 
     */
    public Datalist.DolgPer.Servs.Serv createDatalistDolgPerServsServ() {
        return new Datalist.DolgPer.Servs.Serv();
    }

    /**
     * Create an instance of {@link Datalist.DolgPer.Periods }
     * 
     */
    public Datalist.DolgPer.Periods createDatalistDolgPerPeriods() {
        return new Datalist.DolgPer.Periods();
    }

    /**
     * Create an instance of {@link Datalist.PrefList }
     * 
     */
    public Datalist.PrefList createDatalistPrefList() {
        return new Datalist.PrefList();
    }

    /**
     * Create an instance of {@link Datalist.PrefList.Pref }
     * 
     */
    public Datalist.PrefList.Pref createDatalistPrefListPref() {
        return new Datalist.PrefList.Pref();
    }

    /**
     * Create an instance of {@link Datalist.Owners }
     * 
     */
    public Datalist.Owners createDatalistOwners() {
        return new Datalist.Owners();
    }

    /**
     * Create an instance of {@link Datalist.Docs }
     * 
     */
    public Datalist.Docs createDatalistDocs() {
        return new Datalist.Docs();
    }

    /**
     * Create an instance of {@link Datalist.FlsMan }
     * 
     */
    public Datalist.FlsMan createDatalistFlsMan() {
        return new Datalist.FlsMan();
    }

    /**
     * Create an instance of {@link Datalist.People }
     * 
     */
    public Datalist.People createDatalistPeople() {
        return new Datalist.People();
    }

    /**
     * Create an instance of {@link Datalist.Rooms }
     * 
     */
    public Datalist.Rooms createDatalistRooms() {
        return new Datalist.Rooms();
    }

    /**
     * Create an instance of {@link Datalist.Data }
     * 
     */
    public Datalist.Data createDatalistData() {
        return new Datalist.Data();
    }

    /**
     * Create an instance of {@link Datalist.PartTypeList }
     * 
     */
    public Datalist.PartTypeList createDatalistPartTypeList() {
        return new Datalist.PartTypeList();
    }

    /**
     * Create an instance of {@link Datalist.DolgPer.Servs.Serv.Period }
     * 
     */
    public Datalist.DolgPer.Servs.Serv.Period createDatalistDolgPerServsServPeriod() {
        return new Datalist.DolgPer.Servs.Serv.Period();
    }

    /**
     * Create an instance of {@link Datalist.DolgPer.Periods.Period }
     * 
     */
    public Datalist.DolgPer.Periods.Period createDatalistDolgPerPeriodsPeriod() {
        return new Datalist.DolgPer.Periods.Period();
    }

    /**
     * Create an instance of {@link Datalist.PrefList.Pref.PrefKoefList }
     * 
     */
    public Datalist.PrefList.Pref.PrefKoefList createDatalistPrefListPrefPrefKoefList() {
        return new Datalist.PrefList.Pref.PrefKoefList();
    }

    /**
     * Create an instance of {@link Datalist.Owners.Owner }
     * 
     */
    public Datalist.Owners.Owner createDatalistOwnersOwner() {
        return new Datalist.Owners.Owner();
    }

    /**
     * Create an instance of {@link Datalist.Docs.Doc }
     * 
     */
    public Datalist.Docs.Doc createDatalistDocsDoc() {
        return new Datalist.Docs.Doc();
    }

    /**
     * Create an instance of {@link Datalist.FlsMan.FlsCman }
     * 
     */
    public Datalist.FlsMan.FlsCman createDatalistFlsManFlsCman() {
        return new Datalist.FlsMan.FlsCman();
    }

    /**
     * Create an instance of {@link Datalist.People.Man }
     * 
     */
    public Datalist.People.Man createDatalistPeopleMan() {
        return new Datalist.People.Man();
    }

    /**
     * Create an instance of {@link Datalist.Rooms.Room }
     * 
     */
    public Datalist.Rooms.Room createDatalistRoomsRoom() {
        return new Datalist.Rooms.Room();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Datalist.Docs }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Datalist.Docs }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "docs", scope = Datalist.class)
    public JAXBElement<Datalist.Docs> createDatalistDocs(Datalist.Docs value) {
        return new JAXBElement<Datalist.Docs>(_DatalistDocs_QNAME, Datalist.Docs.class, Datalist.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Datalist.PrefList }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Datalist.PrefList }{@code >}
     */
    @XmlElementDecl(namespace = "", name = "pref_list", scope = Datalist.class)
    public JAXBElement<Datalist.PrefList> createDatalistPrefList(Datalist.PrefList value) {
        return new JAXBElement<Datalist.PrefList>(_DatalistPrefList_QNAME, Datalist.PrefList.class, Datalist.class, value);
    }

}
