//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.02 at 11:11:08 AM MSK 
//


package ru.croc.ugd.ssr.model.integration.dgi;

import java.time.LocalDate;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import ru.reinform.cdp.utils.mapper.xml.LocalDateXmlAdapter;


/**
 * <p>Java class for SuperServiceDGPCourtAndMoneyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SuperServiceDGPCourtAndMoneyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="person_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="affair_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="order_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="new_unom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="new_cadnum" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="FlatNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="AgrData" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="AgrType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AgrNum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="AgrEvent" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CourtData" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="signedAgrFile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SuperServiceDGPCourtAndMoneyType", propOrder = {
    "personId",
    "affairId",
    "orderId",
    "newUnom",
    "newCadnum",
    "flatNumber",
    "agrData",
    "agrType",
    "agrNum",
    "agrEvent",
    "courtData",
    "signedAgrFile"
})
@XmlRootElement(name = "SuperServiceDGPCourtAndMoney")
public class SuperServiceDGPCourtAndMoneyType {

    @XmlElement(name = "person_id", required = true)
    protected String personId;
    @XmlElement(name = "affair_id", required = true)
    protected String affairId;
    @XmlElement(name = "order_id", required = true)
    protected String orderId;
    @XmlElement(name = "new_unom", required = true)
    protected String newUnom;
    @XmlElement(name = "new_cadnum", required = true)
    protected String newCadnum;
    @XmlElement(name = "FlatNumber", required = true)
    protected String flatNumber;
    @XmlElement(name = "AgrData", type = String.class)
    @XmlJavaTypeAdapter(LocalDateXmlAdapter.class)
    @XmlSchemaType(name = "date")
    protected LocalDate agrData;
    @XmlElement(name = "AgrType")
    protected String agrType;
    @XmlElement(name = "AgrNum")
    protected String agrNum;
    @XmlElement(name = "AgrEvent", required = true)
    protected String agrEvent;
    @XmlElement(name = "CourtData", type = String.class)
    @XmlJavaTypeAdapter(LocalDateXmlAdapter.class)
    @XmlSchemaType(name = "date")
    protected LocalDate courtData;
    protected String signedAgrFile;

    /**
     * Gets the value of the personId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonId() {
        return personId;
    }

    /**
     * Sets the value of the personId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonId(String value) {
        this.personId = value;
    }

    /**
     * Gets the value of the affairId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAffairId() {
        return affairId;
    }

    /**
     * Sets the value of the affairId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAffairId(String value) {
        this.affairId = value;
    }

    /**
     * Gets the value of the orderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * Sets the value of the orderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderId(String value) {
        this.orderId = value;
    }

    /**
     * Gets the value of the newUnom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewUnom() {
        return newUnom;
    }

    /**
     * Sets the value of the newUnom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewUnom(String value) {
        this.newUnom = value;
    }

    /**
     * Gets the value of the newCadnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewCadnum() {
        return newCadnum;
    }

    /**
     * Sets the value of the newCadnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewCadnum(String value) {
        this.newCadnum = value;
    }

    /**
     * Gets the value of the flatNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlatNumber() {
        return flatNumber;
    }

    /**
     * Sets the value of the flatNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlatNumber(String value) {
        this.flatNumber = value;
    }

    /**
     * Gets the value of the agrData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public LocalDate getAgrData() {
        return agrData;
    }

    /**
     * Sets the value of the agrData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgrData(LocalDate value) {
        this.agrData = value;
    }

    /**
     * Gets the value of the agrType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgrType() {
        return agrType;
    }

    /**
     * Sets the value of the agrType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgrType(String value) {
        this.agrType = value;
    }

    /**
     * Gets the value of the agrNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgrNum() {
        return agrNum;
    }

    /**
     * Sets the value of the agrNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgrNum(String value) {
        this.agrNum = value;
    }

    /**
     * Gets the value of the agrEvent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgrEvent() {
        return agrEvent;
    }

    /**
     * Sets the value of the agrEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgrEvent(String value) {
        this.agrEvent = value;
    }

    /**
     * Gets the value of the courtData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public LocalDate getCourtData() {
        return courtData;
    }

    /**
     * Sets the value of the courtData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourtData(LocalDate value) {
        this.courtData = value;
    }

    /**
     * Gets the value of the signedAgrFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignedAgrFile() {
        return signedAgrFile;
    }

    /**
     * Sets the value of the signedAgrFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignedAgrFile(String value) {
        this.signedAgrFile = value;
    }

}
