//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.05 at 12:18:22 PM MSK 
//


package ru.croc.ugd.ssr.model.integration.dgi;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import ru.reinform.cdp.utils.mapper.xml.LocalDateXmlAdapter;


/**
 * <p>Java class for SuperServiceDGPStartRemovalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SuperServiceDGPStartRemovalType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="Letter"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="LetterNum" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="LetterDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="SettlementHouses" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="SettlementHouse" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="new_unom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="new_cadnum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="ResettlementHouses"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="ResettlementHouse" maxOccurs="unbounded"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="snos_unom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                 &lt;element name="snos_cadnum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                                 &lt;element name="ResType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                 &lt;element name="Flats" minOccurs="0"&gt;
 *                                                   &lt;complexType&gt;
 *                                                     &lt;complexContent&gt;
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                                         &lt;sequence&gt;
 *                                                           &lt;element name="FlatNumber" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
 *                                                         &lt;/sequence&gt;
 *                                                       &lt;/restriction&gt;
 *                                                     &lt;/complexContent&gt;
 *                                                   &lt;/complexType&gt;
 *                                                 &lt;/element&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="Cip"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="idCIP" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="addressCIP" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="phoneCIP" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="workCIP" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="dateCIP" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SuperServiceDGPStartRemovalType", propOrder = {
    "startDate",
    "letter",
    "settlementHouses"
})
@XmlRootElement(name = "SuperServiceDGPStartRemoval")
public class SuperServiceDGPStartRemovalType {

    @XmlElement(name = "StartDate", required = true, type = String.class)
    @XmlJavaTypeAdapter(LocalDateXmlAdapter.class)
    @XmlSchemaType(name = "date")
    protected LocalDate startDate;
    @XmlElement(name = "Letter", required = true)
    protected Letter letter;
    @XmlElement(name = "SettlementHouses")
    protected SettlementHouses settlementHouses;

    /**
     * Gets the value of the startDate property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public LocalDate getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setStartDate(LocalDate value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the letter property.
     *
     * @return
     *     possible object is
     *     {@link Letter }
     *
     */
    public Letter getLetter() {
        return letter;
    }

    /**
     * Sets the value of the letter property.
     *
     * @param value
     *     allowed object is
     *     {@link Letter }
     *
     */
    public void setLetter(Letter value) {
        this.letter = value;
    }

    /**
     * Gets the value of the settlementHouses property.
     *
     * @return
     *     possible object is
     *     {@link SettlementHouses }
     *
     */
    public SettlementHouses getSettlementHouses() {
        return settlementHouses;
    }

    /**
     * Sets the value of the settlementHouses property.
     *
     * @param value
     *     allowed object is
     *     {@link SettlementHouses }
     *
     */
    public void setSettlementHouses(SettlementHouses value) {
        this.settlementHouses = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="LetterNum" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="LetterDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "letterNum",
        "letterDate"
    })
    public static class Letter {

        @XmlElement(name = "LetterNum", required = true)
        protected String letterNum;
        @XmlElement(name = "LetterDate", required = true, type = String.class)
        @XmlJavaTypeAdapter(LocalDateXmlAdapter.class)
        @XmlSchemaType(name = "date")
        protected LocalDate letterDate;

        /**
         * Gets the value of the letterNum property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getLetterNum() {
            return letterNum;
        }

        /**
         * Sets the value of the letterNum property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setLetterNum(String value) {
            this.letterNum = value;
        }

        /**
         * Gets the value of the letterDate property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public LocalDate getLetterDate() {
            return letterDate;
        }

        /**
         * Sets the value of the letterDate property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setLetterDate(LocalDate value) {
            this.letterDate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="SettlementHouse" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="new_unom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="new_cadnum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="ResettlementHouses"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="ResettlementHouse" maxOccurs="unbounded"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="snos_unom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                       &lt;element name="snos_cadnum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                                       &lt;element name="ResType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                       &lt;element name="Flats" minOccurs="0"&gt;
     *                                         &lt;complexType&gt;
     *                                           &lt;complexContent&gt;
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                               &lt;sequence&gt;
     *                                                 &lt;element name="FlatNumber" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
     *                                               &lt;/sequence&gt;
     *                                             &lt;/restriction&gt;
     *                                           &lt;/complexContent&gt;
     *                                         &lt;/complexType&gt;
     *                                       &lt;/element&gt;
     *                                     &lt;/sequence&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="Cip"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="idCIP" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="addressCIP" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="phoneCIP" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="workCIP" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                             &lt;element name="dateCIP" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "settlementHouse"
    })
    public static class SettlementHouses {

        @XmlElement(name = "SettlementHouse")
        protected List<SettlementHouse> settlementHouse;

        /**
         * Gets the value of the settlementHouse property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the settlementHouse property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSettlementHouse().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SettlementHouse }
         *
         *
         */
        public List<SettlementHouse> getSettlementHouse() {
            if (settlementHouse == null) {
                settlementHouse = new ArrayList<SettlementHouse>();
            }
            return this.settlementHouse;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="new_unom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="new_cadnum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="ResettlementHouses"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="ResettlementHouse" maxOccurs="unbounded"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="snos_unom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                             &lt;element name="snos_cadnum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *                             &lt;element name="ResType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                             &lt;element name="Flats" minOccurs="0"&gt;
         *                               &lt;complexType&gt;
         *                                 &lt;complexContent&gt;
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                                     &lt;sequence&gt;
         *                                       &lt;element name="FlatNumber" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
         *                                     &lt;/sequence&gt;
         *                                   &lt;/restriction&gt;
         *                                 &lt;/complexContent&gt;
         *                               &lt;/complexType&gt;
         *                             &lt;/element&gt;
         *                           &lt;/sequence&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="Cip"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="idCIP" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="addressCIP" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="phoneCIP" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="workCIP" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                   &lt;element name="dateCIP" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "newUnom",
            "newCadnum",
            "resettlementHouses",
            "cip"
        })
        public static class SettlementHouse {

            @XmlElement(name = "new_unom", required = true)
            protected String newUnom;
            @XmlElement(name = "new_cadnum")
            protected String newCadnum;
            @XmlElement(name = "ResettlementHouses", required = true)
            protected ResettlementHouses resettlementHouses;
            @XmlElement(name = "Cip", required = true)
            protected Cip cip;

            /**
             * Gets the value of the newUnom property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getNewUnom() {
                return newUnom;
            }

            /**
             * Sets the value of the newUnom property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setNewUnom(String value) {
                this.newUnom = value;
            }

            /**
             * Gets the value of the newCadnum property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getNewCadnum() {
                return newCadnum;
            }

            /**
             * Sets the value of the newCadnum property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setNewCadnum(String value) {
                this.newCadnum = value;
            }

            /**
             * Gets the value of the resettlementHouses property.
             *
             * @return
             *     possible object is
             *     {@link ResettlementHouses }
             *
             */
            public ResettlementHouses getResettlementHouses() {
                return resettlementHouses;
            }

            /**
             * Sets the value of the resettlementHouses property.
             *
             * @param value
             *     allowed object is
             *     {@link ResettlementHouses }
             *
             */
            public void setResettlementHouses(ResettlementHouses value) {
                this.resettlementHouses = value;
            }

            /**
             * Gets the value of the cip property.
             *
             * @return
             *     possible object is
             *     {@link Cip }
             *
             */
            public Cip getCip() {
                return cip;
            }

            /**
             * Sets the value of the cip property.
             *
             * @param value
             *     allowed object is
             *     {@link Cip }
             *
             */
            public void setCip(Cip value) {
                this.cip = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="idCIP" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="addressCIP" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="phoneCIP" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="workCIP" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *         &lt;element name="dateCIP" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "idCIP",
                "addressCIP",
                "phoneCIP",
                "workCIP",
                "dateCIP"
            })
            public static class Cip {

                @XmlElement(required = true)
                protected String idCIP;
                @XmlElement(required = true)
                protected String addressCIP;
                @XmlElement(required = true)
                protected String phoneCIP;
                @XmlElement(required = true)
                protected String workCIP;
                @XmlElement(required = true, type = String.class)
                @XmlJavaTypeAdapter(LocalDateXmlAdapter.class)
                @XmlSchemaType(name = "date")
                protected LocalDate dateCIP;

                /**
                 * Gets the value of the idCIP property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getIdCIP() {
                    return idCIP;
                }

                /**
                 * Sets the value of the idCIP property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setIdCIP(String value) {
                    this.idCIP = value;
                }

                /**
                 * Gets the value of the addressCIP property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getAddressCIP() {
                    return addressCIP;
                }

                /**
                 * Sets the value of the addressCIP property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setAddressCIP(String value) {
                    this.addressCIP = value;
                }

                /**
                 * Gets the value of the phoneCIP property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getPhoneCIP() {
                    return phoneCIP;
                }

                /**
                 * Sets the value of the phoneCIP property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setPhoneCIP(String value) {
                    this.phoneCIP = value;
                }

                /**
                 * Gets the value of the workCIP property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getWorkCIP() {
                    return workCIP;
                }

                /**
                 * Sets the value of the workCIP property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setWorkCIP(String value) {
                    this.workCIP = value;
                }

                /**
                 * Gets the value of the dateCIP property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public LocalDate getDateCIP() {
                    return dateCIP;
                }

                /**
                 * Sets the value of the dateCIP property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setDateCIP(LocalDate value) {
                    this.dateCIP = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="ResettlementHouse" maxOccurs="unbounded"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="snos_unom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                   &lt;element name="snos_cadnum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
             *                   &lt;element name="ResType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                   &lt;element name="Flats" minOccurs="0"&gt;
             *                     &lt;complexType&gt;
             *                       &lt;complexContent&gt;
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                           &lt;sequence&gt;
             *                             &lt;element name="FlatNumber" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
             *                           &lt;/sequence&gt;
             *                         &lt;/restriction&gt;
             *                       &lt;/complexContent&gt;
             *                     &lt;/complexType&gt;
             *                   &lt;/element&gt;
             *                 &lt;/sequence&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "resettlementHouse"
            })
            public static class ResettlementHouses {

                @XmlElement(name = "ResettlementHouse", required = true)
                protected List<ResettlementHouse> resettlementHouse;

                /**
                 * Gets the value of the resettlementHouse property.
                 *
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the resettlementHouse property.
                 *
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getResettlementHouse().add(newItem);
                 * </pre>
                 *
                 *
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link ResettlementHouse }
                 *
                 *
                 */
                public List<ResettlementHouse> getResettlementHouse() {
                    if (resettlementHouse == null) {
                        resettlementHouse = new ArrayList<ResettlementHouse>();
                    }
                    return this.resettlementHouse;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 *
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 *
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="snos_unom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *         &lt;element name="snos_cadnum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
                 *         &lt;element name="ResType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *         &lt;element name="Flats" minOccurs="0"&gt;
                 *           &lt;complexType&gt;
                 *             &lt;complexContent&gt;
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *                 &lt;sequence&gt;
                 *                   &lt;element name="FlatNumber" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
                 *                 &lt;/sequence&gt;
                 *               &lt;/restriction&gt;
                 *             &lt;/complexContent&gt;
                 *           &lt;/complexType&gt;
                 *         &lt;/element&gt;
                 *       &lt;/sequence&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 *
                 *
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "snosUnom",
                    "snosCadnum",
                    "resType",
                    "flats"
                })
                public static class ResettlementHouse {

                    @XmlElement(name = "snos_unom", required = true)
                    protected String snosUnom;
                    @XmlElement(name = "snos_cadnum")
                    protected String snosCadnum;
                    @XmlElement(name = "ResType", required = true)
                    protected String resType;
                    @XmlElement(name = "Flats")
                    protected Flats flats;

                    /**
                     * Gets the value of the snosUnom property.
                     *
                     * @return
                     *     possible object is
                     *     {@link String }
                     *
                     */
                    public String getSnosUnom() {
                        return snosUnom;
                    }

                    /**
                     * Sets the value of the snosUnom property.
                     *
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *
                     */
                    public void setSnosUnom(String value) {
                        this.snosUnom = value;
                    }

                    /**
                     * Gets the value of the snosCadnum property.
                     *
                     * @return
                     *     possible object is
                     *     {@link String }
                     *
                     */
                    public String getSnosCadnum() {
                        return snosCadnum;
                    }

                    /**
                     * Sets the value of the snosCadnum property.
                     *
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *
                     */
                    public void setSnosCadnum(String value) {
                        this.snosCadnum = value;
                    }

                    /**
                     * Gets the value of the resType property.
                     *
                     * @return
                     *     possible object is
                     *     {@link String }
                     *
                     */
                    public String getResType() {
                        return resType;
                    }

                    /**
                     * Sets the value of the resType property.
                     *
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *
                     */
                    public void setResType(String value) {
                        this.resType = value;
                    }

                    /**
                     * Gets the value of the flats property.
                     *
                     * @return
                     *     possible object is
                     *     {@link Flats }
                     *
                     */
                    public Flats getFlats() {
                        return flats;
                    }

                    /**
                     * Sets the value of the flats property.
                     *
                     * @param value
                     *     allowed object is
                     *     {@link Flats }
                     *
                     */
                    public void setFlats(Flats value) {
                        this.flats = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType&gt;
                     *   &lt;complexContent&gt;
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                     *       &lt;sequence&gt;
                     *         &lt;element name="FlatNumber" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/&gt;
                     *       &lt;/sequence&gt;
                     *     &lt;/restriction&gt;
                     *   &lt;/complexContent&gt;
                     * &lt;/complexType&gt;
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "flatNumber"
                    })
                    public static class Flats {

                        @XmlElement(name = "FlatNumber", required = true)
                        protected List<String> flatNumber;

                        /**
                         * Gets the value of the flatNumber property.
                         * 
                         * <p>
                         * This accessor method returns a reference to the live list,
                         * not a snapshot. Therefore any modification you make to the
                         * returned list will be present inside the JAXB object.
                         * This is why there is not a <CODE>set</CODE> method for the flatNumber property.
                         * 
                         * <p>
                         * For example, to add a new item, do as follows:
                         * <pre>
                         *    getFlatNumber().add(newItem);
                         * </pre>
                         * 
                         * 
                         * <p>
                         * Objects of the following type(s) are allowed in the list
                         * {@link String }
                         * 
                         * 
                         */
                        public List<String> getFlatNumber() {
                            if (flatNumber == null) {
                                flatNumber = new ArrayList<String>();
                            }
                            return this.flatNumber;
                        }

                    }

                }

            }

        }

    }

}
