//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.10.05 at 12:18:22 PM MSK
//

package ru.croc.ugd.ssr.model.integration.dgi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SuperServiceDGPLetterRequestType complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SuperServiceDGPLetterRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="person_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="affair_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="idCIP" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="pdfProposal" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *         &lt;element name="pdfBlank" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="letter_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SuperServiceDGPLetterRequestType",
        propOrder = { "personId", "affairId", "idCIP", "pdfProposal", "pdfBlank", "letterId" })
@XmlRootElement(name = "SuperServiceDGPLetterRequest")
public class SuperServiceDGPLetterRequestType {

    @XmlElement(name = "person_id", required = true)
    protected String personId;

    @XmlElement(name = "affair_id", required = true)
    protected String affairId;

    @XmlElement(required = true)
    protected String idCIP;

    @XmlElement(required = true)
    protected String pdfProposal;

    protected String pdfBlank;

    @XmlElement(name = "letter_id", required = true)
    protected String letterId;

    /**
     * Gets the value of the personId property.
     * 
     * @return possible object is {@link String }
     */
    public String getPersonId() {
        return personId;
    }

    /**
     * Sets the value of the personId property.
     * 
     * @param value
     *            allowed object is {@link String }
     */
    public void setPersonId(String value) {
        this.personId = value;
    }

    /**
     * Gets the value of the affairId property.
     * 
     * @return possible object is {@link String }
     */
    public String getAffairId() {
        return affairId;
    }

    /**
     * Sets the value of the affairId property.
     * 
     * @param value
     *            allowed object is {@link String }
     */
    public void setAffairId(String value) {
        this.affairId = value;
    }

    /**
     * Gets the value of the idCIP property.
     * 
     * @return possible object is {@link String }
     */
    public String getIdCIP() {
        return idCIP;
    }

    /**
     * Sets the value of the idCIP property.
     * 
     * @param value
     *            allowed object is {@link String }
     */
    public void setIdCIP(String value) {
        this.idCIP = value;
    }

    /**
     * Gets the value of the pdfProposal property.
     * 
     * @return possible object is byte[]
     */
    public String getPdfProposal() {
        return pdfProposal;
    }

    /**
     * Sets the value of the pdfProposal property.
     * 
     * @param value
     *            allowed object is byte[]
     */
    public void setPdfProposal(String value) {
        this.pdfProposal = value;
    }

    /**
     * Gets the value of the pdfBlank property.
     * 
     * @return possible object is byte[]
     */
    public String getPdfBlank() {
        return pdfBlank;
    }

    /**
     * Sets the value of the pdfBlank property.
     * 
     * @param value
     *            allowed object is byte[]
     */
    public void setPdfBlank(String value) {
        this.pdfBlank = value;
    }

    /**
     * Gets the value of the letterId property.
     * 
     * @return possible object is {@link String }
     */
    public String getLetterId() {
        return letterId;
    }

    /**
     * Sets the value of the letterId property.
     * 
     * @param value
     *            allowed object is {@link String }
     */
    public void setLetterId(String value) {
        this.letterId = value;
    }

}
