//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.20 at 01:16:44 PM MSK 
//

package ru.croc.ugd.ssr.model.integration.dgi;

import ru.reinform.cdp.utils.mapper.xml.LocalDateTimeXmlAdapter;
import ru.reinform.cdp.utils.mapper.xml.LocalDateXmlAdapter;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for SuperServiceDGPStatementStatusType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SuperServiceDGPStatementStatusType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="affair_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="statementType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="statementDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="declineReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="declineReasonText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="pdfStatement" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="FileLink" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="letter_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="fullDocs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="waitingDocs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="waitingDocsDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="TechInfo" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="userID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="userFIO" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="actionDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SuperServiceDGPStatementStatusType", propOrder = {
    "affairId",
    "statementType",
    "statementDate",
    "declineReason",
    "declineReasonText",
    "fileLink",
    "letterId",
    "fullDocs",
    "waitingDocs",
    "waitingNote",
    "waitingDocsDate",
    "techInfo"
})
@XmlRootElement(name = "SuperServiceDGPStatementStatus")
public class SuperServiceDGPStatementStatusType {

    @XmlElement(name = "affair_id", required = true)
    protected String affairId;
    @XmlElement(required = true)
    protected String statementType;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(LocalDateXmlAdapter.class)
    @XmlSchemaType(name = "date")
    protected LocalDate statementDate;
    protected String declineReason;
    protected String declineReasonText;
    @XmlElement(name = "FileLink")
    protected String fileLink;
    @XmlElement(name = "letter_id", required = true)
    protected String letterId;
    protected String fullDocs;
    protected SuperServiceDGPStatementStatusType.WaitingDocs waitingDocs;
    protected String waitingNote;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(LocalDateXmlAdapter.class)
    @XmlSchemaType(name = "date")
    protected LocalDate waitingDocsDate;
    @XmlElement(name = "TechInfo")
    protected SuperServiceDGPStatementStatusType.TechInfo techInfo;

    /**
     * Gets the value of the affairId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAffairId() {
        return affairId;
    }

    /**
     * Sets the value of the affairId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAffairId(String value) {
        this.affairId = value;
    }

    /**
     * Gets the value of the statementType property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getStatementType() {
        return statementType;
    }

    /**
     * Sets the value of the statementType property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setStatementType(String value) {
        this.statementType = value;
    }

    /**
     * Gets the value of the statementDate property.
     *
     * @return
     *     possible object is
     *     {@link LocalDate }
     *
     */
    public LocalDate getStatementDate() {
        return statementDate;
    }

    /**
     * Sets the value of the statementDate property.
     *
     * @param value
     *     allowed object is
     *     {@link LocalDate }
     *
     */
    public void setStatementDate(LocalDate value) {
        this.statementDate = value;
    }

    /**
     * Gets the value of the declineReason property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDeclineReason() {
        return declineReason;
    }

    /**
     * Sets the value of the declineReason property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDeclineReason(String value) {
        this.declineReason = value;
    }

    /**
     * Gets the value of the declineReasonText property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDeclineReasonText() {
        return declineReasonText;
    }

    /**
     * Sets the value of the declineReasonText property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDeclineReasonText(String value) {
        this.declineReasonText = value;
    }

    /**
     * Gets the value of the fileLink property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFileLink() {
        return fileLink;
    }

    /**
     * Sets the value of the fileLink property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFileLink(String value) {
        this.fileLink = value;
    }

    /**
     * Gets the value of the letterId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLetterId() {
        return letterId;
    }

    /**
     * Sets the value of the letterId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLetterId(String value) {
        this.letterId = value;
    }

    /**
     * Gets the value of the fullDocs property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFullDocs() {
        return fullDocs;
    }

    /**
     * Sets the value of the fullDocs property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFullDocs(String value) {
        this.fullDocs = value;
    }

    /**
     * Gets the value of the waitingDocs property.
     *
     * @return
     *     possible object is
     *     {@link SuperServiceDGPStatementStatusType.WaitingDocs }
     *
     */
    public SuperServiceDGPStatementStatusType.WaitingDocs getWaitingDocs() {
        return waitingDocs;
    }

    /**
     * Sets the value of the waitingDocs property.
     *
     * @param value
     *     allowed object is
     *     {@link SuperServiceDGPStatementStatusType.WaitingDocs }
     *
     */
    public void setWaitingDocs(SuperServiceDGPStatementStatusType.WaitingDocs value) {
        this.waitingDocs = value;
    }

    /**
     * Gets the value of the waitingNote property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getWaitingNote() {
        return waitingNote;
    }

    /**
     * Sets the value of the waitingNote property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setWaitingNote(String value) {
        this.waitingNote = value;
    }

    /**
     * Gets the value of the waitingDocsDate property.
     *
     * @return
     *     possible object is
     *     {@link LocalDate }
     *
     */
    public LocalDate getWaitingDocsDate() {
        return waitingDocsDate;
    }

    /**
     * Sets the value of the waitingDocsDate property.
     *
     * @param value
     *     allowed object is
     *     {@link LocalDate }
     *
     */
    public void setWaitingDocsDate(LocalDate value) {
        this.waitingDocsDate = value;
    }

    /**
     * Gets the value of the techInfo property.
     *
     * @return
     *     possible object is
     *     {@link SuperServiceDGPStatementStatusType.TechInfo }
     *
     */
    public SuperServiceDGPStatementStatusType.TechInfo getTechInfo() {
        return techInfo;
    }

    /**
     * Sets the value of the techInfo property.
     *
     * @param value
     *     allowed object is
     *     {@link SuperServiceDGPStatementStatusType.TechInfo }
     *
     */
    public void setTechInfo(SuperServiceDGPStatementStatusType.TechInfo value) {
        this.techInfo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="userID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="userFIO" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="actionDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userID",
        "userFIO",
        "actionDateTime"
    })
    public static class TechInfo {

        @XmlElement(required = true)
        protected String userID;
        @XmlElement(required = true)
        protected String userFIO;
        @XmlElement(required = true, type = String.class)
        @XmlJavaTypeAdapter(LocalDateTimeXmlAdapter.class)
        @XmlSchemaType(name = "dateTime")
        protected LocalDateTime actionDateTime;

        /**
         * Gets the value of the userID property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getUserID() {
            return userID;
        }

        /**
         * Sets the value of the userID property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setUserID(String value) {
            this.userID = value;
        }

        /**
         * Gets the value of the userFIO property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getUserFIO() {
            return userFIO;
        }

        /**
         * Sets the value of the userFIO property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setUserFIO(String value) {
            this.userFIO = value;
        }

        /**
         * Gets the value of the actionDateTime property.
         *
         * @return
         *     possible object is
         *     {@link LocalDateTime }
         *
         */
        public LocalDateTime getActionDateTime() {
            return actionDateTime;
        }

        /**
         * Sets the value of the actionDateTime property.
         *
         * @param value
         *     allowed object is
         *     {@link LocalDateTime }
         *
         */
        public void setActionDateTime(LocalDateTime value) {
            this.actionDateTime = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="docId" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "doc"
    })
    public static class WaitingDocs {

        @XmlElement(required = true)
        protected List<WaitingDocs.Doc> doc;

        public List<WaitingDocs.Doc> getDoc() {
            if (doc == null) {
                doc = new ArrayList<>();
            }
            return this.doc;
        }

        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "docId",
                "docName"
        })
        public static class Doc {

            @XmlElement(required = true)
            protected String docId;

            @XmlElement(required = true)
            protected String docName;

            public String getDocId() {
                return this.docId;
            }

            public String getDocName() {
                return this.docName;
            }

        }

    }

}
