//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.05 at 12:18:22 PM MSK 
//


package ru.croc.ugd.ssr.model.integration.dgi;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SuperServiceDGPPersonsResult" type="{http://www.ugd.croc.ru/ssr/model/integration/dgi}SuperServiceDGPPersonsMessageType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "superServiceDGPPersonsResult"
})
@XmlRootElement(name = "SuperServiceDGPPersonsMessage")
public class SuperServiceDGPPersonsMessage {

    @XmlElement(name = "SuperServiceDGPPersonsResult")
    protected List<SuperServiceDGPPersonsMessageType> superServiceDGPPersonsResult;

    /**
     * Gets the value of the superServiceDGPPersonsResult property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the superServiceDGPPersonsResult property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSuperServiceDGPPersonsResult().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SuperServiceDGPPersonsMessageType }
     * 
     * 
     */
    public List<SuperServiceDGPPersonsMessageType> getSuperServiceDGPPersonsResult() {
        if (superServiceDGPPersonsResult == null) {
            superServiceDGPPersonsResult = new ArrayList<SuperServiceDGPPersonsMessageType>();
        }
        return this.superServiceDGPPersonsResult;
    }

}
