//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.05 at 12:18:22 PM MSK 
//


package ru.croc.ugd.ssr.model.integration.dgi;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for SuperServiceDGPRemovalStatusType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SuperServiceDGPRemovalStatusType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="new_unom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="new_cadnum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="FlatNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="RemovalStatus" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SuperServiceDGPRemovalStatusType", propOrder = {
    "newUnom",
    "newCadnum",
    "flatNumber",
    "removalStatus"
})
@XmlRootElement(name = "SuperServiceDGPRemovalStatus")
public class SuperServiceDGPRemovalStatusType {

    @XmlElement(name = "new_unom", required = true)
    protected String newUnom;
    @XmlElement(name = "new_cadnum")
    protected String newCadnum;
    @XmlElement(name = "FlatNumber", required = true)
    protected String flatNumber;
    @XmlElement(name = "RemovalStatus")
    protected List<String> removalStatus;

    /**
     * Gets the value of the newUnom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewUnom() {
        return newUnom;
    }

    /**
     * Sets the value of the newUnom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewUnom(String value) {
        this.newUnom = value;
    }

    /**
     * Gets the value of the newCadnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewCadnum() {
        return newCadnum;
    }

    /**
     * Sets the value of the newCadnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewCadnum(String value) {
        this.newCadnum = value;
    }

    /**
     * Gets the value of the flatNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlatNumber() {
        return flatNumber;
    }

    /**
     * Sets the value of the flatNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlatNumber(String value) {
        this.flatNumber = value;
    }

    /**
     * Gets the value of the removalStatus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the removalStatus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRemovalStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRemovalStatus() {
        if (removalStatus == null) {
            removalStatus = new ArrayList<String>();
        }
        return this.removalStatus;
    }

}
