//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.02 at 11:11:08 AM MSK 
//


package ru.croc.ugd.ssr.model.integration.dgi;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for SuperServiceDGPSettleFlatInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SuperServiceDGPSettleFlatInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="person_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="affair_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="order_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="new_unom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="new_cadnum" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="FlatNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SuperServiceDGPSettleFlatInfoType", propOrder = {
    "personId",
    "affairId",
    "orderId",
    "newUnom",
    "newCadnum",
    "flatNumber"
})
@XmlRootElement(name = "SuperServiceDGPSettleFlatInfo")
public class SuperServiceDGPSettleFlatInfoType {

    @XmlElement(name = "person_id", required = true)
    protected String personId;
    @XmlElement(name = "affair_id", required = true)
    protected String affairId;
    @XmlElement(name = "order_id", required = true)
    protected String orderId;
    @XmlElement(name = "new_unom", required = true)
    protected String newUnom;
    @XmlElement(name = "new_cadnum", required = true)
    protected String newCadnum;
    @XmlElement(name = "FlatNumber", required = true)
    protected String flatNumber;

    /**
     * Gets the value of the personId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonId() {
        return personId;
    }

    /**
     * Sets the value of the personId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonId(String value) {
        this.personId = value;
    }

    /**
     * Gets the value of the affairId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAffairId() {
        return affairId;
    }

    /**
     * Sets the value of the affairId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAffairId(String value) {
        this.affairId = value;
    }

    /**
     * Gets the value of the orderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * Sets the value of the orderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderId(String value) {
        this.orderId = value;
    }

    /**
     * Gets the value of the newUnom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewUnom() {
        return newUnom;
    }

    /**
     * Sets the value of the newUnom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewUnom(String value) {
        this.newUnom = value;
    }

    /**
     * Gets the value of the newCadnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewCadnum() {
        return newCadnum;
    }

    /**
     * Sets the value of the newCadnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewCadnum(String value) {
        this.newCadnum = value;
    }

    /**
     * Gets the value of the flatNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlatNumber() {
        return flatNumber;
    }

    /**
     * Sets the value of the flatNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlatNumber(String value) {
        this.flatNumber = value;
    }

}
