//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.20 at 01:16:44 PM MSK 
//


package ru.croc.ugd.ssr.model.integration.dgi;

import ru.reinform.cdp.utils.mapper.xml.LocalDateTimeXmlAdapter;
import ru.reinform.cdp.utils.mapper.xml.LocalDateXmlAdapter;

import java.time.LocalDate;
import java.time.LocalDateTime;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for SuperServiceDGPViewStatusType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SuperServiceDGPViewStatusType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="person_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="affair_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="letter_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="viewDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="annotation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TechInfo" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="userID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="userFIO" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="actionDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SuperServiceDGPViewStatusType", propOrder = {
    "personId",
    "affairId",
    "letterId",
    "viewDate",
    "annotation",
    "techInfo"
})
@XmlRootElement(name = "SuperServiceDGPViewStatus")
public class SuperServiceDGPViewStatusType {

    @XmlElement(name = "person_id", required = true)
    protected String personId;
    @XmlElement(name = "affair_id", required = true)
    protected String affairId;
    @XmlElement(name = "letter_id", required = true)
    protected String letterId;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(LocalDateXmlAdapter.class)
    @XmlSchemaType(name = "date")
    protected LocalDate viewDate;
    protected String annotation;
    @XmlElement(name = "TechInfo")
    protected SuperServiceDGPViewStatusType.TechInfo techInfo;

    /**
     * Gets the value of the personId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPersonId() {
        return personId;
    }

    /**
     * Sets the value of the personId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPersonId(String value) {
        this.personId = value;
    }

    /**
     * Gets the value of the affairId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAffairId() {
        return affairId;
    }

    /**
     * Sets the value of the affairId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAffairId(String value) {
        this.affairId = value;
    }

    /**
     * Gets the value of the letterId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLetterId() {
        return letterId;
    }

    /**
     * Sets the value of the letterId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLetterId(String value) {
        this.letterId = value;
    }

    /**
     * Gets the value of the viewDate property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public LocalDate getViewDate() {
        return viewDate;
    }

    /**
     * Sets the value of the viewDate property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setViewDate(LocalDate value) {
        this.viewDate = value;
    }

    /**
     * Gets the value of the annotation property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAnnotation() {
        return annotation;
    }

    /**
     * Sets the value of the annotation property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAnnotation(String value) {
        this.annotation = value;
    }

    /**
     * Gets the value of the techInfo property.
     *
     * @return
     *     possible object is
     *     {@link SuperServiceDGPViewStatusType.TechInfo }
     *
     */
    public SuperServiceDGPViewStatusType.TechInfo getTechInfo() {
        return techInfo;
    }

    /**
     * Sets the value of the techInfo property.
     *
     * @param value
     *     allowed object is
     *     {@link SuperServiceDGPViewStatusType.TechInfo }
     *
     */
    public void setTechInfo(SuperServiceDGPViewStatusType.TechInfo value) {
        this.techInfo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="userID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="userFIO" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="actionDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userID",
        "userFIO",
        "actionDateTime"
    })
    public static class TechInfo {

        @XmlElement(required = true)
        protected String userID;
        @XmlElement(required = true)
        protected String userFIO;
        @XmlElement(required = true, type = String.class)
        @XmlJavaTypeAdapter(LocalDateTimeXmlAdapter.class)
        @XmlSchemaType(name = "dateTime")
        protected LocalDateTime actionDateTime;

        /**
         * Gets the value of the userID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUserID() {
            return userID;
        }

        /**
         * Sets the value of the userID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUserID(String value) {
            this.userID = value;
        }

        /**
         * Gets the value of the userFIO property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUserFIO() {
            return userFIO;
        }

        /**
         * Sets the value of the userFIO property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUserFIO(String value) {
            this.userFIO = value;
        }

        /**
         * Gets the value of the actionDateTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public LocalDateTime getActionDateTime() {
            return actionDateTime;
        }

        /**
         * Sets the value of the actionDateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActionDateTime(LocalDateTime value) {
            this.actionDateTime = value;
        }

    }

}
