//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.05 at 12:18:22 PM MSK 
//


package ru.croc.ugd.ssr.model.integration.dgi;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import ru.reinform.cdp.utils.mapper.xml.LocalDateXmlAdapter;


/**
 * <p>Java class for SuperServiceDGPPersonsMessageType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SuperServiceDGPPersonsMessageType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="person_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="actual_date" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="snils" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="lastname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="firstname" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="middlename" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="birthdate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="sex" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="IsQueue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="IsDead" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ChangeStatus" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="delReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="LinkedFlats" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Flat" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="affair_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="statusLiving" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="encumbrances" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="snos_unom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="snos_cadnum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="snos_flat_num" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="snos_rooms_num" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                             &lt;element name="noFlat" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="isFederal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="inCourt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SuperServiceDGPPersonsMessageType", propOrder = {
    "personId",
    "actualDate",
    "snils",
    "lastname",
    "firstname",
    "middlename",
    "birthdate",
    "sex",
    "isQueue",
    "isDead",
    "changeStatus",
    "delReason",
    "linkedFlats"
})
public class SuperServiceDGPPersonsMessageType {

    @XmlElement(name = "person_id", required = true)
    protected String personId;
    @XmlElement(name = "actual_date", required = true, type = String.class)
    @XmlJavaTypeAdapter(LocalDateXmlAdapter.class)
    @XmlSchemaType(name = "date")
    protected LocalDate actualDate;
    protected String snils;
    @XmlElement(required = true)
    protected String lastname;
    @XmlElement(required = true)
    protected String firstname;
    protected String middlename;
    @XmlElement(type = String.class)
    @XmlJavaTypeAdapter(LocalDateXmlAdapter.class)
    @XmlSchemaType(name = "date")
    protected LocalDate birthdate;
    @XmlElement(required = true)
    protected String sex;
    @XmlElement(name = "IsQueue")
    protected String isQueue;
    @XmlElement(name = "IsDead")
    protected String isDead;
    @XmlElement(name = "ChangeStatus", required = true)
    protected String changeStatus;
    protected String delReason;
    @XmlElement(name = "LinkedFlats")
    protected LinkedFlats linkedFlats;

    /**
     * Gets the value of the personId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPersonId() {
        return personId;
    }

    /**
     * Sets the value of the personId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPersonId(String value) {
        this.personId = value;
    }

    /**
     * Gets the value of the actualDate property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public LocalDate getActualDate() {
        return actualDate;
    }

    /**
     * Sets the value of the actualDate property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setActualDate(LocalDate value) {
        this.actualDate = value;
    }

    /**
     * Gets the value of the snils property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSnils() {
        return snils;
    }

    /**
     * Sets the value of the snils property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSnils(String value) {
        this.snils = value;
    }

    /**
     * Gets the value of the lastname property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * Sets the value of the lastname property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLastname(String value) {
        this.lastname = value;
    }

    /**
     * Gets the value of the firstname property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getFirstname() {
        return firstname;
    }

    /**
     * Sets the value of the firstname property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setFirstname(String value) {
        this.firstname = value;
    }

    /**
     * Gets the value of the middlename property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMiddlename() {
        return middlename;
    }

    /**
     * Sets the value of the middlename property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMiddlename(String value) {
        this.middlename = value;
    }

    /**
     * Gets the value of the birthdate property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public LocalDate getBirthdate() {
        return birthdate;
    }

    /**
     * Sets the value of the birthdate property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBirthdate(LocalDate value) {
        this.birthdate = value;
    }

    /**
     * Gets the value of the sex property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSex() {
        return sex;
    }

    /**
     * Sets the value of the sex property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSex(String value) {
        this.sex = value;
    }

    /**
     * Gets the value of the isQueue property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIsQueue() {
        return isQueue;
    }

    /**
     * Sets the value of the isQueue property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIsQueue(String value) {
        this.isQueue = value;
    }

    /**
     * Gets the value of the isDead property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIsDead() {
        return isDead;
    }

    /**
     * Sets the value of the isDead property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIsDead(String value) {
        this.isDead = value;
    }

    /**
     * Gets the value of the changeStatus property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getChangeStatus() {
        return changeStatus;
    }

    /**
     * Sets the value of the changeStatus property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setChangeStatus(String value) {
        this.changeStatus = value;
    }

    /**
     * Gets the value of the delReason property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDelReason() {
        return delReason;
    }

    /**
     * Sets the value of the delReason property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDelReason(String value) {
        this.delReason = value;
    }

    /**
     * Gets the value of the linkedFlats property.
     *
     * @return
     *     possible object is
     *     {@link LinkedFlats }
     *
     */
    public LinkedFlats getLinkedFlats() {
        return linkedFlats;
    }

    /**
     * Sets the value of the linkedFlats property.
     *
     * @param value
     *     allowed object is
     *     {@link LinkedFlats }
     *
     */
    public void setLinkedFlats(LinkedFlats value) {
        this.linkedFlats = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Flat" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="affair_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="statusLiving" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="encumbrances" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="snos_unom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="snos_cadnum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="snos_flat_num" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="snos_rooms_num" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
     *                   &lt;element name="noFlat" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="isFederal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="inCourt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "flat"
    })
    public static class LinkedFlats {

        @XmlElement(name = "Flat", required = true)
        protected List<Flat> flat;

        /**
         * Gets the value of the flat property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the flat property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFlat().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Flat }
         *
         *
         */
        public List<Flat> getFlat() {
            if (flat == null) {
                flat = new ArrayList<Flat>();
            }
            return this.flat;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="affair_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="statusLiving" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="encumbrances" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="snos_unom" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="snos_cadnum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="snos_flat_num" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="snos_rooms_num" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
         *         &lt;element name="noFlat" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="isFederal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="inCourt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "affairId",
            "statusLiving",
            "encumbrances",
            "snosUnom",
            "snosCadnum",
            "snosFlatNum",
            "snosRoomsNum",
            "noFlat",
            "isFederal",
            "inCourt"
        })
        public static class Flat {

            @XmlElement(name = "affair_id", required = true)
            protected String affairId;
            @XmlElement(required = true)
            protected String statusLiving;
            protected String encumbrances;
            @XmlElement(name = "snos_unom", required = true)
            protected String snosUnom;
            @XmlElement(name = "snos_cadnum")
            protected String snosCadnum;
            @XmlElement(name = "snos_flat_num", required = true)
            protected String snosFlatNum;
            @XmlElement(name = "snos_rooms_num")
            protected List<String> snosRoomsNum;
            protected String noFlat;
            protected String isFederal;
            protected String inCourt;

            /**
             * Gets the value of the affairId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAffairId() {
                return affairId;
            }

            /**
             * Sets the value of the affairId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAffairId(String value) {
                this.affairId = value;
            }

            /**
             * Gets the value of the statusLiving property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStatusLiving() {
                return statusLiving;
            }

            /**
             * Sets the value of the statusLiving property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStatusLiving(String value) {
                this.statusLiving = value;
            }

            /**
             * Gets the value of the encumbrances property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEncumbrances() {
                return encumbrances;
            }

            /**
             * Sets the value of the encumbrances property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEncumbrances(String value) {
                this.encumbrances = value;
            }

            /**
             * Gets the value of the snosUnom property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSnosUnom() {
                return snosUnom;
            }

            /**
             * Sets the value of the snosUnom property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSnosUnom(String value) {
                this.snosUnom = value;
            }

            /**
             * Gets the value of the snosCadnum property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSnosCadnum() {
                return snosCadnum;
            }

            /**
             * Sets the value of the snosCadnum property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSnosCadnum(String value) {
                this.snosCadnum = value;
            }

            /**
             * Gets the value of the snosFlatNum property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSnosFlatNum() {
                return snosFlatNum;
            }

            /**
             * Sets the value of the snosFlatNum property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSnosFlatNum(String value) {
                this.snosFlatNum = value;
            }

            /**
             * Gets the value of the snosRoomsNum property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the snosRoomsNum property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSnosRoomsNum().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getSnosRoomsNum() {
                if (snosRoomsNum == null) {
                    snosRoomsNum = new ArrayList<String>();
                }
                return this.snosRoomsNum;
            }

            /**
             * Gets the value of the noFlat property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNoFlat() {
                return noFlat;
            }

            /**
             * Sets the value of the noFlat property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNoFlat(String value) {
                this.noFlat = value;
            }

            /**
             * Gets the value of the isFederal property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIsFederal() {
                return isFederal;
            }

            /**
             * Sets the value of the isFederal property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIsFederal(String value) {
                this.isFederal = value;
            }

            /**
             * Gets the value of the inCourt property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInCourt() {
                return inCourt;
            }

            /**
             * Sets the value of the inCourt property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInCourt(String value) {
                this.inCourt = value;
            }

        }

    }

}
