//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.02 at 11:11:08 AM MSK 
//


package ru.croc.ugd.ssr.model.integration.dgi;

import java.time.LocalDate;
import java.time.LocalDateTime;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import ru.reinform.cdp.utils.mapper.xml.LocalDateTimeXmlAdapter;
import ru.reinform.cdp.utils.mapper.xml.LocalDateXmlAdapter;


/**
 * <p>Java class for SuperServiceDGPSignAgreementStatusType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SuperServiceDGPSignAgreementStatusType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="affair_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="order_id" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="pdfSignedAgr" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="signDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="TechInfo" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="userID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="userFIO" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="actionDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SuperServiceDGPSignAgreementStatusType", propOrder = {
    "affairId",
    "orderId",
    "pdfSignedAgr",
    "signDate",
    "techInfo"
})
@XmlRootElement(name = "SuperServiceDGPSignAgreementStatus")
public class SuperServiceDGPSignAgreementStatusType {

    @XmlElement(name = "affair_id", required = true)
    protected String affairId;
    @XmlElement(name = "order_id", required = true)
    protected String orderId;
    @XmlElement(required = true)
    protected String pdfSignedAgr;
    @XmlElement(required = true, type = String.class)
    @XmlJavaTypeAdapter(LocalDateXmlAdapter.class)
    @XmlSchemaType(name = "date")
    protected LocalDate signDate;
    @XmlElement(name = "TechInfo")
    protected SuperServiceDGPSignAgreementStatusType.TechInfo techInfo;

    /**
     * Gets the value of the affairId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAffairId() {
        return affairId;
    }

    /**
     * Sets the value of the affairId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAffairId(String value) {
        this.affairId = value;
    }

    /**
     * Gets the value of the orderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * Sets the value of the orderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderId(String value) {
        this.orderId = value;
    }

    /**
     * Gets the value of the pdfSignedAgr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPdfSignedAgr() {
        return pdfSignedAgr;
    }

    /**
     * Sets the value of the pdfSignedAgr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPdfSignedAgr(String value) {
        this.pdfSignedAgr = value;
    }

    /**
     * Gets the value of the signDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public LocalDate getSignDate() {
        return signDate;
    }

    /**
     * Sets the value of the signDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignDate(LocalDate value) {
        this.signDate = value;
    }

    /**
     * Gets the value of the techInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SuperServiceDGPSignAgreementStatusType.TechInfo }
     *     
     */
    public SuperServiceDGPSignAgreementStatusType.TechInfo getTechInfo() {
        return techInfo;
    }

    /**
     * Sets the value of the techInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SuperServiceDGPSignAgreementStatusType.TechInfo }
     *     
     */
    public void setTechInfo(SuperServiceDGPSignAgreementStatusType.TechInfo value) {
        this.techInfo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="userID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="userFIO" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="actionDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userID",
        "userFIO",
        "actionDateTime"
    })
    public static class TechInfo {

        @XmlElement(required = true)
        protected String userID;
        @XmlElement(required = true)
        protected String userFIO;
        @XmlElement(required = true, type = String.class)
        @XmlJavaTypeAdapter(LocalDateTimeXmlAdapter.class)
        @XmlSchemaType(name = "dateTime")
        protected LocalDateTime actionDateTime;

        /**
         * Gets the value of the userID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUserID() {
            return userID;
        }

        /**
         * Sets the value of the userID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUserID(String value) {
            this.userID = value;
        }

        /**
         * Gets the value of the userFIO property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUserFIO() {
            return userFIO;
        }

        /**
         * Sets the value of the userFIO property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUserFIO(String value) {
            this.userFIO = value;
        }

        /**
         * Gets the value of the actionDateTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public LocalDateTime getActionDateTime() {
            return actionDateTime;
        }

        /**
         * Sets the value of the actionDateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActionDateTime(LocalDateTime value) {
            this.actionDateTime = value;
        }

    }

}
