//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.05 at 12:18:22 PM MSK 
//


package ru.croc.ugd.ssr.model.integration.dgi;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="p_unom" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="p_cadastr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "SuperServiceDGPPersonsRequest")
public class SuperServiceDGPPersonsRequest {

    @XmlElement(name = "p_unom")
    protected int pUnom;
    @XmlElement(name = "p_cadastr")
    protected String pCadastr;

    /**
     * Gets the value of the pUnom property.
     * 
     */
    public int getPUnom() {
        return pUnom;
    }

    /**
     * Sets the value of the pUnom property.
     * 
     */
    public void setPUnom(int value) {
        this.pUnom = value;
    }

    /**
     * Gets the value of the pCadastr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCadastr() {
        return pCadastr;
    }

    /**
     * Sets the value of the pCadastr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCadastr(String value) {
        this.pCadastr = value;
    }

}
